name: chit_chat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  connectivity_plus: ^6.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_messaging: 15.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  image_picker: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.0 
  rive: ^0.13.1
  flutter_local_notifications: ^17.1.0
  cached_network_image: ^3.3.1
  firebase_storage: ^12.1.0
  animations: ^2.0.11
  shared_preferences: ^2.2.3
  gap: ^3.0.1
  popover: ^0.3.0+1
 


flutter_native_splash:
  web: false
  image: assets/icon/splash_icon.png
  # background_image: assets/images/bg-login.jpg
  color: "#d6e2ea"
  android: true

  android_12:
    image: assets/icon/splash_icon.png
    color: "#d6e2ea"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash:
  flutter_launcher_icons: ^0.13.1



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
 
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/rivfiles/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: "Roboto-Regular"
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf

    - family: "Roboto-Bold"
      fonts:
        - asset: fonts/Roboto/Roboto-Bold.ttf

    - family: "Roboto-Medium"
      fonts:
        - asset: fonts/Roboto/Roboto-Medium.ttf

    - family: "Roboto-Light"
      fonts:
        - asset: fonts/Roboto/Roboto-Light.ttf
    - family: "Roboto-B"
      fonts:
        - asset: fonts/Roboto/Roboto-Light.ttf
