name: chit_chat
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.2

environment:
  sdk: ^3.5.1

dependencies:
  animated_theme_switcher: ^2.0.10
  animated_toggle_switch: ^0.8.3
  animations: ^2.0.11
  audio_session: ^0.1.21
  audio_waveforms: ^1.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  lottie: ^3.1.2
  open_file_plus: ^3.4.1+1
  package_info_plus: ^8.0.2
  path:
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  popover: ^0.3.0+1
  record: ^5.2.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.2
  timer_count_down: ^2.2.2
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: 
  flutter_launcher_icons: 

flutter_native_splash:
  web: false
  image: assets/icon/splash_icon.png
  color: "#d6e2ea"
  android: true

  android_12:
    image: assets/icon/splash_icon.png
    color: "#d6e2ea"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Icon/app_icon.png"
  adaptive_icon_foreground: "assets/Icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
 

flutter:
 uses-material-design: true
 assets:
    - assets/
    - assets/images/
    - assets/rivfiles/
    - assets/svg/
    - assets/lottie/

 fonts:
    - family: "Roboto-Regular"
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        
    - family: "Roboto-Bold"
      fonts:
        - asset: fonts/Roboto/Roboto-Bold.ttf

    - family: "Roboto-Medium"
      fonts:
        - asset: fonts/Roboto/Roboto-Medium.ttf
